### PR TITLE
Add links to badges in README

### PR DESCRIPTION
**Pull request by szepeviktor**
...and put title First

Look great!

kép

### CODE REVIEW

**Comment by szepeviktor** [comment]
The Coveralls token may not be available to PR-s:

```
Submitting to https://coveralls.io/api/v1/jobs
Client error occurred. status: 422 Unprocessable Entity
Couldn't find a repository matching this job.
```

Do open-source projects need a token??

**Review by sj-i — APPROVED** [review]
:+1:

**Comment by sj-i** [comment]
@szepeviktor 
Thanks!

> The Coveralls token may not be available to PR-s:

It seems that php-coveralls doesn't work well with PRs in GitHub Actions.
https://github.com/php-coveralls/php-coveralls/pull/275
I'll migrate to codecov or [a fork](https://github.com/twinh/php-coveralls#github-actions) of php-coveralls.

**Comment by szepeviktor** [comment]
Please be aware that Coveralls is the superior service.

**Comment by szepeviktor** [comment]
Look what I've found! https://github.com/marketplace/actions/coveralls-github-action

Sending PR....

**Pull request merged**
